### ISSUE TITLE
[Screenshot] - Switch to Groovy gradle

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#205]
Currently the screenshot service is using Kotlin. While I have not gripes with Kotlin it makes maintaining two backends more difficult when they are supposed to be very similar. 

For a new comer I would look at the /server/build.gradle

**Comment by smzoha** [comment]
Hi @R-Sandor, I'd like to give this a shot. Can you please assign this issue to me?

Also, since I'm participating in Hacktoberfest this year, would it be possible for you to add the "hacktoberfest" tag to this issue or the pull request, please?

**Comment by smzoha** [comment]
Hi @R-Sandor, I'd like to take a shot at this, if that's alright.
Also, I'm participating in Hacktoberfest this year and would love to have this contribution count toward my progress. Would it be possible for you to please assign the "hacktoberfest" label to this issue, if I'm assigned to work on it?

Thank you!

**Comment by R-Sandor** [comment]
@smzoha Absolutely! Thank you for the help. It shouldn't be too difficult but I am here if you have any questions or suggestions. 

Thanks!
