### ISSUE TITLE
Remove deprications in gradle files

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#213]
There is a warning that `task depends on` or similar is deprecated among the Gradle builds.

**Comment by smzoha** [comment]
Hi @R-Sandor, I did a bit of digging around this and found that the currently used version of Sonar in the project will always throw the notice indicating deprecated behavior, unless the following property is specified along with the gradle command:

`-Dsonar.gradle.skipCompile=true`

This can be included in the `makefile`, but I feel that wouldn't be ideal. The ideal way would be to upgrade the dependency to version 5.x, preferably the latest one.

Please let me know your thoughts and I can get started on this (obviously, if you assign me, that is) 😁

**Comment by R-Sandor** [comment]
@smzoha, Thanks for researching this for me! Would you mind upgrading the version to the latest?

**Comment by smzoha** [comment]
@R-Sandor Consider it done! 😀
