### ISSUE TITLE
[Server] Update Bookmark to have scrapable field

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#221]
- [ ]  needs #220

**Comment by R-Sandor** [comment]
@vijay-kesanakurthi Would you mind if I give you the #220 as well since this one too since it needs it?

**Comment by vijay-kesanakurthi** [comment]
Sure,, assign me that one too.

**Comment by vijay-kesanakurthi** [comment]
Yes add me.
