### ISSUE TITLE
[Server] BookmarkService AddBookmark Check if scrapable is toggled

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#223]
# Details 
We don't want to scrape a website that the user has request or that system may determine is not scrapable 
## Requires
- [ ] Check AddBmkReq if scrapable is true. Don't scrap if its not scrapable.
- [ ] JSoup doesn't run.
- [ ] sManager doesn't run. 
- [ ] Title is set the same as the url for the default. 
- [ ] ScreenshotUrl is set to `""` i.e. empty string.
- [ ] Unit test `/server/src/test/java/dev/findfirst/core/controller/BookmarkController.java`
  - Create a test with a bookmark that is not scrapable and ensure the Bookmark returned does not have screenshotUrl or JSoup set title. 
  - A good test would be a bookmark that we know has a successful scrape and that without the toggled field doesn't set the data.

**Comment by smzoha** [comment]
Hi @R-Sandor, can I try my hand at this? Thanks!

**Comment by R-Sandor** [comment]
@smzoha Absolutely, thanks! Let me know if you have any questions.

**Comment by smzoha** [comment]
@R-Sandor what should be the default behavior - i.e. should scrapable be true by default, as it is currently?

There are places where instances of `AddBkmkReq` are created (for example, BookmarkService.java:213 and the unit tests).

**Comment by R-Sandor** [comment]
Yup, the default behavior should be to have scrapable toggled from the frontend on the request. 

This ticket is on the server side so it should check that field on the incoming request from the frontend.

**Comment by smzoha** [comment]
@R-Sandor from what I gathered from the **Import Bookmarks** feature, it seemingly takes in an html file and adds the bookmarks to the application based on the `href` values available inside the anchor tags of the page.

How do we determine if `scrapable` should be true/false in that case?

**Comment by R-Sandor** [comment]
#226 still needs to be scoped out, its almost an epic in its own right, so I am not expecting you to complete that issue too.

**Comment by R-Sandor** [comment]
Whoops, I said 226 at first I meant #236, it all backend. No obligation that one would definitely be a bit more work because of all the pieces. I plan on breaking it up.

**Comment by smzoha** [comment]
Hi @R-Sandor, I have implemented the code, but have found an issue that needs to be addressed on the frontend, in order for the application to work properly.

Since the `scrapable` field in the `AddBkmkReq` is a boolean, it will default to `false` when the `scrapable` value is not sent in from the UI. As such, it would prompt the method in the `BookmarkService` to always skip the scrapping and taking a screenshot.

Should get the pull-request up with the changes in the backend now? Or should I wait until you add the toggle in the frontend?

**Comment by R-Sandor** [comment]
Thank you @smzoha for the work and pointing that out. I would go ahead put the PR in then I will make the change to addBkmkReq to true by default on the frontend until we add the the toggle check box. 

Then I will merge your PR and everything will be in working order! :rocket:

**Comment by smzoha** [comment]
@R-Sandor sounds cool. I'll get the PR up then.
