### ISSUE TITLE
Intergrate Flyway with TestContainers

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#225]

**Comment by JinnJarBurger** [comment]
@R-Sandor could you assign this issue to me?

**Comment by R-Sandor** [comment]
Awesome! Thanks @JinnJarBurger. To run integration tests you can either add this parameter on the gradlew `-Dspring.profiles.active=integration`

or change the server/build.gradle  line 113 to this
`  systemProperty 'spring.profiles.active', 'integration'`

I turned it off temporarily because I need to be more careful on what sites I am continuously webscraping in my integration tests. I will switch back once I pick some sites that always allow with very little rate limiting.

**Comment by JinnJarBurger** [comment]
> Right now I kind of use the init schema stuff for integration testing. 
> 
> `sever/src/main/resources/application-integration.java` but that's not one to one with how my flyway works on an empty database.

Alright then, I will get started with this and let you know if I have any more queries regarding this.

**Comment by R-Sandor** [comment]
Hey no problem! I am not in a big rush as this doesn't break anything but I do appreciate the help so thank you.

**Comment by JinnJarBurger** [comment]
Hello @R-Sandor extremely sorry for the late reply, I am finally back. It looks like you have already configured a lot of the `flyway` configuration (including the init schemas and the gradle build file), are you planning on completing this then?

**Comment by R-Sandor** [comment]
@JinnJarBurger Yeah sorry about that looks like there were probably some changes over time from when this was made. I will just clean up the integration file close this ticket out! 

Sorry man!

**Comment by JinnJarBurger** [comment]
> @JinnJarBurger Yeah sorry about that looks like there were probably some changes over time from when this was made. I will just clean up the integration file close this ticket out!
> 
> Sorry man!

all good!
