### ISSUE TITLE
[Frontend/Backend] - Bookmark already exists error

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#226]
# Backend 
Handle the error for when a bookmark already exists when a user tries to send a request to add a bookmark. 
- Consider making a custom exception.

EDIT:
# Frontend 
- create a toast message that is in the bottom right of the screen with the error message.

**Comment by Barny37** [comment]
Hello can i work on this issue ??

**Comment by R-Sandor** [comment]
Absolutely, there is minor change from when I wrote this issue.  The frontend no long waits to clear the new bookmark. 
My thoughts are add notification toast like this one: https://getbootstrap.com/docs/5.0/components/toasts/

Play around with adding some bookmarks to get a feel and I am open to suggestions! 

@Barny37 welcome to FindFirst!

**Comment by Barny37** [comment]
Hi, I downloaded a project where on the backend already exist BookmarkAlreadyExistsException, so i used it. When this exception is triggered, it sends a Conflict (Error 409) to the frontend. However, I’m having trouble signing in on the frontend while using docker compose staging, so I can’t test if the toast notifications are working. Do you know about this problem or how to fix it??

**Comment by R-Sandor** [comment]
@Barny37 Please don't use staging, please you the development profile. This has come up before I will have to update the docs and probably just remove the staging compose.

**Comment by R-Sandor** [comment]
Closing this issue! Thanks again. Please feel free to grab anything else that interest you, and if there isn't anything yet check later :D We got a lot of new features to add!
