### ISSUE TITLE
[Frontend] search bar at the top 

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#232]
# Details
- When the screen is very small and is on a mobile device ensure that the search occupies the top of the screen just underneath the navigation buttons. 
- On wider devices and desktop browsers the search bar should be between all the elements at the top.

# Requirements: 
- [ ] Provide screenshots of the design 
  - [ ] wide screens
  - [ ] mobile view

**Comment by shravya-chepa** [comment]
Hello, can I work on this?
