### ISSUE TITLE
[Screenshot] - Encode the screnshot URI using http library

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#235]
- One of the problems I think that we're facing is inconsistent representation of URI's. For example %20 should be represented as a `<space>`  ASCII character.
- This needs to happen in the screenshot service when the screenshot is saved. 

- [ ] Use java.net.URLDecoder.decode() and then apply the slash replacement.

**Comment by smzoha** [comment]
Hi @R-Sandor. I'll take this, if that's okay.

**Comment by R-Sandor** [comment]
@smzoha Its all yours :smile:
