### ISSUE TITLE
[Frontend] Add toggle for scrapable to a valid NewBookmark Card

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#244]
- [ ] Toggle should be check box that appears in the card on a valid bookmark.

**Comment by Nikkaa13** [comment]
I would like to work on this issue. Could you assign it to me please?

**Comment by R-Sandor** [comment]
Thanks @Nikkaa13, All yours! Let me know if you have any questions.

**Comment by R-Sandor** [comment]
@Nikkaa13 Sorry I went ahead and completed the ticket! Thanks for your help though.
