### ISSUE TITLE
[Server] Create SearchController.java 

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#250]
# Details
When search bar is complete we should be able to leverage the search to find bookmarks and tags. 

## Requirements
Create rest mappings for the following.
- [ ] Create endpoint mapping /api/search
- [ ] /api/search/tags
  - Search for bookmarks with a given tag. 
- [ ] /api/search/title
  - Search for a bookmark based on words in the title.
- [ ] /api/search/text
  - Used for full text search. 

Implementing these functions will be done by subsequent issues.

**Comment by apurvabanka** [comment]
@R-Sandor I am interested in working on this issue. Can you assign this to me?

**Comment by R-Sandor** [comment]
@apurvabanka Certainly, Thank you for helping FindFirst! :rocket:
