### ISSUE TITLE
[Frontend] Search results change bookmarkList

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#252]
# Once a user has run a query update the fronted to reflect the results. 

- [x] Update the bookmarkList
  - leverage the dispatch context with the results of the query.
needs #232
needs #255 
needs #251

**Comment by nilaridis** [comment]
Hi, I'd like to work on this issue. I'll investigate how the bookmark list is being modified during search and ensure that it remains stable while showing search results separately. Let me know if you have any specific guidelines or suggestions before I begin!

**Comment by R-Sandor** [comment]
@nilaridis Hey! Welcome. I had some undocumented dependencies which I have just updated. I would love to give you this ticket though, just need to wait on the search bar on the frontend, and the backend API.

**Comment by nilaridis** [comment]
Hey! Okey sure , no problem . Let me know when the search bar is ready
