### ISSUE TITLE
[Frontend] Add API call to frontend API for search

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#263]
# Details
After the searchbar has been added we need to add functionality to `frontend/api/Api.ts`

# Tasks 
- [x] Create Get methods in the Api.ts that match https://github.com/R-Sandor/FindFirst/blob/main/server/src/main/java/dev/findfirst/core/controller/SearchController.java#L22

**Comment by vthuan-dev** [comment]
i would like to help u , pls assigne me

**Comment by R-Sandor** [comment]
@vthuan-dev Sounds good! Thank you!

**Comment by vthuan-dev** [comment]
hi , did you set up backend for this issue ?

**Comment by strifee0903** [comment]
Hi, I'm gravitate toward this issue. I have some idea since I've worked on this a couple times and can open a PR to discuss further. Thanks for considering me.

**Comment by thob2112011** [comment]
Maybe I can participate in solving this issue then #264. Can you assign me?

**Comment by R-Sandor** [comment]
@vthuan-dev Hey sorry for the late reply here. Been busy week with a new born. The end points are there but they don't return anything yet. 

I still the frontend to have the HTTP.GET though to mirror the uri.

**Comment by AchuthRKumar** [comment]
I am new here and still working on it. Please excuse me if i am slow.

**Comment by R-Sandor** [comment]
Do you have any questions? 

The API endpoints that you're adding are in this file:
https://github.com/R-Sandor/FindFirst/blob/main/server/src/main/java/dev/findfirst/core/controller/SearchController.java#L22

You'll need to look at that signature at the top of the Get Mapping then add a similar path to the api.ts
https://github.com/R-Sandor/FindFirst/blob/main/server/src/main/java/dev/findfirst/core/controller/SearchController.java#L22

So yours might look something like 
```
searchBookmarksByTitle(title: string) { 
  return instance.get("PATH",  searchBkmkByTitleReq) // copy the same params located in Java
} 
```
RequestBody fields: 

https://github.com/R-Sandor/FindFirst/blob/main/server/src/main/java/dev/findfirst/core/model/SearchBkmkByTitleReq.java

Example of the request body  json object: 
```
{
  title: "the search title here"
}
```

**Comment by R-Sandor** [comment]
@AchuthRKumar, Yeah that's a little bit of a hurdle because we don't have it connect to the search bar yet #262

**Comment by R-Sandor** [comment]
Hey I am closing the ticket. I started working on it because of that hurdle we talked about above.

**Comment by R-Sandor** [comment]
@AchuthRKumar thank you for your help!
