### ISSUE TITLE
[Frontend] Searchbar leverages Api to search

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#264]
# Details 
This issue needs R-Sandor/FindFirst#263 to begin work. After the user as began typing search for the bookmark or bookmarks with a given tag, e.g. please use the the Api.ts.

# Tasks 
- [x] Populate the bookmarkList from the results of the search query.

**Comment by thob2112011** [comment]
Could you please assign me to this project? I would love the opportunity to collaborate and help out.
Thank you for considering my request!

**Comment by R-Sandor** [comment]
@thob2112011 Absolutely! Thanks, and welcome to FindFirst.
