### ISSUE TITLE
[Server] Url encode on import 

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#266]
# Details 
There is a bug that might be caused on the import modal caused by the url being decoded: 
https://github.com/R-Sandor/FindFirst/blob/main/server/src/main/java/dev/findfirst/core/service/BookmarkService.java#L207
Intern the error might cause the import to partially fail. 

# Tasks 
- [ ] Get use the same URL decode found on addBookmark

**Comment by smzoha** [comment]
Hi @R-Sandor, I would like to take a look at this. 

Can you please outline what sort of behavior the bug is producing in the application?

Do you have any specific flow that I can follow to reproduce this error at all times (or any URL affected by this issue)?

**Comment by R-Sandor** [comment]
@smzoha absolutely! Appreciate the help too! 

The problem I am seeing is in the import of a bookmarks file. In dev it always works but in production the import sort of just works in the background and the GUI should be receiving the data back but it gets an error about an unexpected character, I think this is the result url encoding error.

**Comment by R-Sandor** [comment]
@smzoha I have sample import data in `/data/bookmarks`.

**Comment by smzoha** [comment]
@R-Sandor I'll see what I can find.

**Comment by R-Sandor** [comment]
@smzoha Thanks! I will try to capture some screenshots for you too.

**Comment by smzoha** [comment]
@R-Sandor I tried a few different types of URLs, tried some of the sample bookmarks provided in the project as well, but alas, couldn't find any exception crop up in my test cases.

I tried importing a non-encoded URL and JSoup seemingly did the encoding here, so I feel that might not be the issue here. If you manage to gather some more information around this, I'd be happy to take another look.

**Comment by R-Sandor** [comment]
@smzoha I took a look at it yesterday, it looks like its not a URL issues. It seems like there is a problem with how Flux is behaving when its deployed on the server. 

It appears to return all the bookmarks at once rather than one at a time in the usual behavior for Flux and in the dev environment (i.e. one's own machine).

**Comment by R-Sandor** [comment]
@smzoha I am going to leave this issue open but unassigned because now its not breaking anything with the frontend handling all the bookmarks at once if Flux is broken. I am just not sure why Flux would behave differently.

**Comment by smzoha** [comment]
@R-Sandor, that is alright. I haven't been able to look into this recently. If anyone can figure out the reason behind it, that'd be awesome (and would be enlightening).

**Comment by R-Sandor** [comment]
@smzoha Hey I wanted to let you know I did figure this out. Ends up being an issue with Nginx buffering the proxy. 

https://stackoverflow.com/questions/72522550/nginx-as-reverse-proxy-for-spring-webflux-changes-streaming-behavior

**Comment by R-Sandor** [comment]
@smzoha Thank you again for helping debug this :1st_place_medal:
