### ISSUE TITLE
[Frontend] - Refactor searchbar into its own component. 

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#284]
# Details 
The Navbar component is getting messy with much of the code in it being for the search functionality. 

## Tasks 
- [ ] Create a Searchbar.tsx in `/components/Navbar`
- [ ] Add the refactored component back to the Navbar component.

**Comment by samr874** [comment]
@R-Sandor what is the status of this issue ?? keep me updated about this issue ??

**Comment by R-Sandor** [comment]
@samr874 Hey! Thanks for reaching out. I was a little AFK over Christmas. I would have loved to give this to you but I already completed the refactor last week. Thank you for reminding me to close this!
