### ISSUE TITLE
Get Website Preview Pictures for bookmarks

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#5]
Ideally microservice to grab screen grabs of websites that are bookmarked would be a good solution.

A tool like Puppeteer would be useful.

**Comment by oxr463** [comment]
Reference(s):
- https://github.com/microsoft/playwright-java
- https://docs.gradle.org/current/userguide/part1_gradle_init.html

**Comment by oxr463** [comment]
```
curl 'http://localhost:8080/screenshot?url=http://foo.com'
```

**Comment by R-Sandor** [comment]
Marking this as done. Thanks @oxr463!
