### ISSUE TITLE
As a User I want a preview of the Bookmarked Site on the Card display

### ISSUE THREAD

**Issue by R-Sandor** [R-Sandor/FindFirst#92]

**Comment by antonrasmussen** [comment]
@R-Sandor I'm down to work on this next. Not sure how to assign myself.

**Comment by R-Sandor** [comment]
@antonrasmussen Sounds good man! I assigned it too you. 
It should be pretty cool one honestly. 

I thinking that the preview is image over the card as the background. Open to some ideas though, as text over the image preview may be too much. 

https://getbootstrap.com/docs/4.0/components/card/

As for the scrapping part I would look at something like playwright: 
https://www.zenrows.com/blog/playwright-screenshot#avoid-getting-blocked
